version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"
    insecure-external-code-execution: "deny"
    target-branch: "develop"
    groups:
      pip-packages:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"
    target-branch: "develop"
    groups:
      docker-packages:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"
    target-branch: "develop"
    groups:
      gh-actions-packages:
        patterns:
          - "*"

