version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"
    insecure-external-code-execution: "deny"
    target-branch: "develop"
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"
    insecure-external-code-execution: "deny"
    target-branch: "develop"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"
    target-branch: "develop"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "update"
    target-branch: "develop"

