FROM python:alpine

WORKDIR /app

RUN ["apk", "add", "gcc", "musl-dev", "libffi-dev", "openssl-dev", "python3-dev"]

COPY requirements.txt setup.py scripts/get_root_key.py /app/
COPY connaisseur /app/connaisseur

RUN ["pip3", "install", "-r", "/app/requirements.txt"]
RUN ["pip3", "install", "/app"]
RUN ["pip3", "install", "cryptography"]

ENTRYPOINT [ "python3", "/app/get_root_key.py" ]