FROM alpine:3

RUN apk add --no-cache curl && \
    curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && \
    chmod +x ./kubectl && \
    mv ./kubectl /usr/local/bin/kubectl && \
    apk del curl

# Harden image
COPY docker/harden.sh /
RUN sh /harden.sh && rm /harden.sh

COPY scripts/helm_hook.sh /

ENTRYPOINT ["ash", "/helm_hook.sh"]
