FROM debian:bullseye@sha256:ab2b95aa8d7d6d54866b92c322cf0693933c1ae8038652f24ddfda1d1763a45a

COPY ./test/integration/notary_service_container/ test/integration/notary_service_container/
COPY ./test/integration/notary_init.sh test/integration/notary_init.sh
COPY ./test/integration/notary_addhash.sh test/integration/notary_addhash.sh

RUN apt update &&\
    apt upgrade -y && \
    apt install -y docker notary expect ca-certificates && \
    cp ./test/integration/notary_service_container/server/ca.crt /usr/local/share/ca-certificates/notary_root_ca.crt && \
    update-ca-certificates

ARG DIGEST
ENV DIGEST=${DIGEST}

CMD [ "bash", "-c", "./test/integration/notary_init.sh && ./test/integration/notary_addhash.sh ${DIGEST}" ]
