name: cleanup registry

on:
  workflow_call:

permissions: {}

jobs:
  cleanup-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup test images in 'connaisseur-test'
        uses: snok/container-retention-policy@2ebfab771446f9cde79044dab61eec867ac1d62b # v2.1.1
        with:
          image-names: connaisseur-test
          cut-off: three weeks ago UTC+1
          timestamp-to-use: updated_at
          account-type: org
          org-name: sse-secure-systems
          token: ${{ secrets.GHCR_PAT }}
      - name: Cleanup dangling images without tag
        uses: snok/container-retention-policy@2ebfab771446f9cde79044dab61eec867ac1d62b # v2.1.1
        with:
          image-names: connaisseur*
          untagged-only: true
          cut-off: four hours ago UTC+1
          timestamp-to-use: updated_at
          account-type: org
          org-name: sse-secure-systems
          token: ${{ secrets.GHCR_PAT }}
      - name: Cleanup all connaisseur images
        uses: snok/container-retention-policy@2ebfab771446f9cde79044dab61eec867ac1d62b # v2.1.1
        with:
          image-names: connaisseur
          skip-tags: master, develop, v*, sha256-*
          cut-off: four days ago UTC+1
          timestamp-to-use: updated_at
          account-type: org
          org-name: sse-secure-systems
          token: ${{ secrets.GHCR_PAT }}
