name: pr

permissions: {}

on:
  pull_request:
    branches:
      - master
      - develop

defaults:
  run:
    shell: bash

jobs:
  ci:
    uses: ./.github/workflows/100_ci.yml
    permissions:
      packages: write
      contents: read
      security-events: write
      # pull-requests: read
    #   id-token: write
    #   actions: read
    #   checks: read
    #   deployments: read
    #   issues: read
    #   discussions: read
    #   pages: read
    #   repository-projects: read
    #   statuses: read
    #   attestations: read
    secrets: inherit
    with:
      run_build: all
      run_compliance_checks: none
      run_unit_tests: none
      run_sast: none
      output_type: table