name: pr

permissions: {}

on:
  pull_request:
    branches:
      - master
      - develop

concurrency:
  group: pr-${{ github.head_ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  ci:
    uses: ./.github/workflows/100_ci.yml
    permissions:
      packages: write
      contents: write
      security-events: write
    secrets: inherit
