name: ci

permissions: {}

on:
  workflow_call:
    inputs:
      run_build:
        description: "Which build jobs should be run: 'all', 'required', 'none'?"
        type: string
        default: "all"
        required: false
      run_compliance_checks:
        description: "Which compliance checks should be run: 'all', 'required', 'none'?"
        type: string
        default: "all"
        required: false
      run_unit_tests:
        description: "Which unit tests should be run: 'all', 'required', 'none'?"
        type: string
        default: "all"
        required: false
      run_sast:
        description: "Which sast jobs should be run: 'all', 'required', 'none'?"
        type: string
        default: "all"
        required: false
      run_sca:
        description: "Which sca jobs should be run: 'all', 'required', 'none'?"
        type: string
        default: "all"
        required: false
      run_docs:
        description: "Which doc jobs should be run: 'all', 'required', 'none'?"
        type: string
        default: "all"
        required: false
      run_integration_tests:
        description: "Which integration tests should be run: 'all', 'required', 'none'?"
        type: string
        default: "all"
        required: false
      output_type:
        description: 'Output either "sarif" (GITHUB_TOKEN with security-events:write) or print results as "table" and fail on error'
        type: string
        default: 'sarif'
        required: false

defaults:
  run:
    shell: bash

jobs:
  ci-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Show ci settings
        run: |
          get_output() { case "$1" in "all") echo ":white_check_mark:";; "required") echo ":information_source:";; "none") echo ":x:";; *) echo "Unknown value";; esac; }
          echo "# :pencil: CI Settings" >> ${GITHUB_STEP_SUMMARY}
          echo "<table>" >> ${GITHUB_STEP_SUMMARY}
          echo "<tr><th>Setting</th><th>Value</th></tr>" >> ${GITHUB_STEP_SUMMARY}
          echo "<tr><td>Run Docs</td><td>$(get_output ${{ inputs.run_docs }})</td></tr>" >> ${GITHUB_STEP_SUMMARY}
          echo "<tr><td>Run Build</td><td>$(get_output ${{ inputs.run_build }})</td></tr>" >> ${GITHUB_STEP_SUMMARY}
          echo "<tr><td>Run Compliance</td><td>$(get_output ${{ inputs.run_compliance_checks }})</td></tr>" >> ${GITHUB_STEP_SUMMARY}
          echo "<tr><td>Run Unit Tests</td><td>$(get_output ${{ inputs.run_unit_tests }})</td></tr>" >> ${GITHUB_STEP_SUMMARY}
          echo "<tr><td>Run SAST</td><td>$(get_output ${{ inputs.run_sast }})</td></tr>" >> ${GITHUB_STEP_SUMMARY}
          echo "<tr><td>Run SCA</td><td>$(get_output ${{ inputs.run_sca }})</td></tr>" >> ${GITHUB_STEP_SUMMARY}
          echo "<tr><td>Run Integration Tests</td><td>$(get_output ${{ inputs.run_integration_tests }})</td></tr>" >> ${GITHUB_STEP_SUMMARY}
          echo "<tr><td>Report type</td><td><code>${{ inputs.output_type }}</code></td></tr>" >> ${GITHUB_STEP_SUMMARY}
          echo "</table>" >> ${GITHUB_STEP_SUMMARY}
          echo "($(get_output 'all') - run all jobs, $(get_output 'required') - run important/required jobs only, $(get_output 'none') - skip jobs)" >> ${GITHUB_STEP_SUMMARY}
          echo "" >> ${GITHUB_STEP_SUMMARY}

  build:
    uses: ./.github/workflows/101_build.yml
    needs: [ci-settings]
    permissions:
      packages: write
    secrets: inherit
    with:
      run_build: ${{ inputs.run_build }}

  compliance:
    uses: ./.github/workflows/102_compliance.yml
    needs: [ci-settings]
    permissions:
      contents: read
    with:
      run_compliance_checks: ${{ inputs.run_compliance_checks }}

  unit-test:
    uses: ./.github/workflows/103_unit-test.yml
    needs: [ci-settings]
    with:
      run_unit_tests: ${{ inputs.run_unit_tests }}

  sast:
    uses: ./.github/workflows/104_sast.yml
    needs: [ci-settings]
    permissions:
      security-events: write
    with:
      run_sast: ${{ inputs.run_sast }}
      output: ${{ inputs.output_type }}

  # sca:
  #   uses: ./.github/workflows/sca.yml
  #   needs: [conditionals, build]
  #   permissions:
  #     contents: write
  #     security-events: write
  #     packages: read
  #   secrets: inherit
  #   with:
  #     registry: ${{ needs.build.outputs.build_registry }}
  #     repo_owner: ${{ github.repository_owner }}
  #     image: ${{ needs.build.outputs.build_image }}
  #     skip: ${{ needs.conditionals.outputs.skip_sca }}
  #     output: ${{ needs.conditionals.outputs.output_type }}

  # docs:
  #   uses: ./.github/workflows/docs.yaml
  #   needs: [conditionals]
  #   permissions:
  #     contents: write
  #   with:
  #     skip: ${{ needs.conditionals.outputs.skip_docs }}

  # integration-test:
  #   uses: ./.github/workflows/integration-test.yml
  #   needs: [conditionals, build]
  #   permissions:
  #     packages: read
  #   secrets: inherit
  #   with:
  #     build_registry: ${{ needs.build.outputs.build_registry }}
  #     repo_owner: ${{ github.repository_owner }}
  #     build_image_repository: ${{ needs.build.outputs.build_registry }}/${{ needs.build.outputs.build_repo }}
  #     build_tag: ${{ needs.build.outputs.build_tag }}
  #     skip: ${{ needs.conditionals.outputs.skip_integration_tests }}
  #     cosign_public_key: ${{ needs.build.outputs.cosign_public_key }}
