name: sast

on:
  workflow_call:
    inputs:
      jobs_to_run:
        description: "Which sast jobs should be run: 'all', 'only-required', 'skip-all'?"
        type: string
        default: "all"
      output:
        description: 'Output either "sarif" (GITHUB_TOKEN with security-events:write) or print results as "table" and fail on error'
        type: string
        required: false
        default: 'sarif'

permissions: {}

jobs:
  codeql:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.jobs_to_run == 'all' &&
      inputs.output == 'sarif'
    permissions:
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@c793b717bc78562f491db7b0e93a3a178b099162 # v4.32.5
        with:
          languages: 'go'
      - name: Analyze
        uses: github/codeql-action/analyze@c793b717bc78562f491db7b0e93a3a178b099162 # v4.32.5

  golangci-lint:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.jobs_to_run != 'skip-all'
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          cache: false
          go-version: '1.25'
      - name: Analyze cmd
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: latest
          args: '--timeout=10m --tests=false'
          working-directory: cmd
      - name: Analyze internal
        uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20 # v9.2.0
        with:
          version: latest
          args: '--timeout=10m --tests=false'
          working-directory: internal

  gosec:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.jobs_to_run != 'skip-all'
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Analyze
        uses: securego/gosec@bb17e422fc34bf4c0a2e5cab9d07dc45a68c040c # v2.24.7
        with:
          args: "-exclude-dir=test -exclude-dir=tools ${{ inputs.output == 'sarif' && '-no-fail -fmt sarif -out gosec-results.sarif' || '-fmt text' }} ./..."
      - name: Upload
        uses: github/codeql-action/upload-sarif@c793b717bc78562f491db7b0e93a3a178b099162 # v4.32.5
        if: inputs.output == 'sarif'
        with:
          sarif_file: 'gosec-results.sarif'

  hadolint:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.jobs_to_run == 'all'
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Scan
        uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
        with:
          dockerfile: build/Dockerfile
          format: ${{ inputs.output == 'sarif' && 'sarif' || 'tty' }}
          no-fail: ${{ inputs.output == 'sarif' && 'true' || 'false' }}
          output-file: ${{ inputs.output == 'sarif' && 'hadolint-results.sarif' || '' }}
      - name: Upload
        uses: github/codeql-action/upload-sarif@c793b717bc78562f491db7b0e93a3a178b099162 # v4.32.5
        if: inputs.output == 'sarif'
        with:
          sarif_file: 'hadolint-results.sarif'

  kubelinter:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.jobs_to_run == 'all'
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Scan
        uses: stackrox/kube-linter-action@87802a2f4e01abebb3ee3c67a3002fea71f6eae5 # v1.0.7
        with:
          config: .github/.kube-linter/config.yaml
          directory: charts/connaisseur
          format: ${{ inputs.output == 'sarif' && 'sarif' || 'plain' }}
          output-file: ${{ inputs.output == 'sarif' && 'kubelinter-results.sarif' || 'kube-linter.log' }}
      - name: Upload
        uses: github/codeql-action/upload-sarif@c793b717bc78562f491db7b0e93a3a178b099162 # v4.32.5
        if: inputs.output == 'sarif'
        with:
          sarif_file: 'kubelinter-results.sarif'

  trivy-config-scan:
    name: trivy config
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.jobs_to_run == 'all'
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create reports folder
        run: |
          mkdir reports
        shell: bash
      - name: Render Helm charts
        run: |
          mkdir deployment
          helm template charts/connaisseur > deployment/deployment.yaml
        shell: bash
      - name: Scan deployment.yaml
        uses: aquasecurity/trivy-action@97e0b3872f55f89b95b2f65b3dbab56962816478 # v0.34.2
        with:
          scan-type: config
          scan-ref: deployment
          format: ${{ inputs.output }}
          output: ${{ inputs.output == 'sarif' && 'reports/trivy-k8s-results.sarif' || '' }}
      - name: Scan Dockerfiles
        uses: aquasecurity/trivy-action@97e0b3872f55f89b95b2f65b3dbab56962816478 # v0.34.2
        with:
          scan-type: config
          scan-ref: build
          format: ${{ inputs.output }}
          output: ${{ inputs.output == 'sarif' && 'reports/trivy-docker-results.sarif' || '' }}
      - name: Upload k8s report
        uses: github/codeql-action/upload-sarif@c793b717bc78562f491db7b0e93a3a178b099162 # v4.32.5
        if: inputs.output == 'sarif'
        with:
          sarif_file: 'reports/trivy-k8s-results.sarif'
          category: 'k8s'
      - name: Upload docker report
        uses: github/codeql-action/upload-sarif@c793b717bc78562f491db7b0e93a3a178b099162 # v4.32.5
        if: inputs.output == 'sarif'
        with:
          sarif_file: 'reports/trivy-docker-results.sarif'
          category: 'docker'
