name: sca

permissions: {}

on:
  workflow_call:
    inputs:
      image:
        description: "Image used for testing, i.e. registry + repository + tag"
        type: string
        required: true
      registry:
        description: 'Registry to login to pull image, e.g. "ghcr.io" for GHCR, leave empty if image is public'
        type: string
        required: false
        default: ''
      repo_owner:
        description: 'Name of repository owner, e.g. "github.repository_owner" for ghcr.io'
        type: string
        required: false
        default: ''
      jobs_to_run:
        description: "Which sca jobs should be run: 'all', 'only-required', 'skip-all'?"
        type: string
        default: "all"
      output:
        description: 'Output either "sarif" (GITHUB_TOKEN with security-events:write) or print results as "table" and fail on error'
        type: string
        required: false
        default: 'sarif'

jobs:
  trivy-image-scan:
    name: trivy image
    runs-on: ubuntu-latest
    if: inputs.jobs_to_run != 'skip-all'
    permissions:
      packages: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Login with registry
        if: inputs.registry != ''
        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.repo_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Create reports folder
        run: |
          mkdir reports
        shell: bash
      - name: Run Trivy on image
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: ${{ inputs.image }}
          scan-type: "image"
          format: ${{ inputs.output == 'sarif' && 'sarif' || 'table' }}
          output: ${{ inputs.output == 'sarif' && 'reports/trivy-vuln-results.sarif' || '/dev/stdout' }}
          exit-code: ${{ inputs.output == 'sarif' && '0' || '1' }}
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db # Workaround for https://github.com/aquasecurity/trivy-action/issues/389
          TRIVY_JAVA_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-java-db,public.ecr.aws/aquasecurity/trivy-java-db # Workaround for https://github.com/aquasecurity/trivy-action/issues/389
      - name: Upload
        if: inputs.output == 'sarif'
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        with:
          sarif_file: 'reports'
