name: k8s-version-config
description: 'action to prepare testing different k8s versions'
inputs:
  k8s-version:
    description: 'k8s version to be tested'
    required: true
  load-local-image:
    description: K3S channel (https://update.k3s.io/v1-release/channels)
    required: false
    default: true
runs:
  using: "composite"
  steps:
    - name: Install yq and bash
      run: |
        sudo snap install yq
        sudo apt update
        sudo apt install bash -y
      shell: bash
    - uses: ./.github/actions/k3s-cluster
      with:
        k3s-channel: ${{ inputs.k8s-version }}
    - name: Adjust Configuration
      run: |
        if [[ $(echo "${{ inputs.k8s-version }}" | tail -c 3) -lt "19" ]]; then
          yq e 'del(.deployment.securityContext.seccompProfile)' -i helm/values.yaml
          yq e '.deployment.annotations."seccomp.security.alpha.kubernetes.io/pod" = "runtime/default"' -i helm/values.yaml
        fi
      shell: bash
    - name: Load Image
      run: |
        if ${{ inputs.load-local-image }}
        then
          sudo k3s ctr images import ${GITHUB_SHA}_image.tar;
        fi
      shell: bash
